import { RegionNode, lagosGranular, fctGranular, edoGranular, accraGranular, nairobiGranular } from './regions-data-granular.js';

export { RegionNode, lagosGranular, fctGranular, edoGranular, accraGranular, nairobiGranular };

export const regionTree: RegionNode[] = [
  {
    id: 'africa',
    type: 'CONTINENT',
    name: 'Africa',
    code: 'AF',
    isCovered: true,
    children: [
      {
        id: 'nigeria',
        type: 'COUNTRY',
        name: 'Nigeria',
        code: 'NG',
        isCovered: true,
        children: [
          { id: 'ng-abia', type: 'STATE', name: 'Abia', code: 'AB' },
          { id: 'ng-adamawa', type: 'STATE', name: 'Adamawa', code: 'AD' },
          { id: 'ng-akwa-ibom', type: 'STATE', name: 'Akwa Ibom', code: 'AK' },
          { id: 'ng-anambra', type: 'STATE', name: 'Anambra', code: 'AN' },
          { id: 'ng-bauchi', type: 'STATE', name: 'Bauchi', code: 'BA' },
          { id: 'ng-bayelsa', type: 'STATE', name: 'Bayelsa', code: 'BY' },
          { id: 'ng-benue', type: 'STATE', name: 'Benue', code: 'BE' },
          { id: 'ng-borno', type: 'STATE', name: 'Borno', code: 'BO' },
          { id: 'ng-cross-river', type: 'STATE', name: 'Cross River', code: 'CR' },
          { id: 'ng-delta', type: 'STATE', name: 'Delta', code: 'DE' },
          { id: 'ng-ebonyi', type: 'STATE', name: 'Ebonyi', code: 'EB' },
          edoGranular,
          { id: 'ng-ekiti', type: 'STATE', name: 'Ekiti', code: 'EK' },
          { id: 'ng-enugu', type: 'STATE', name: 'Enugu', code: 'EN' },
          { id: 'ng-gombe', type: 'STATE', name: 'Gombe', code: 'GO' },
          { id: 'ng-imo', type: 'STATE', name: 'Imo', code: 'IM' },
          { id: 'ng-jigawa', type: 'STATE', name: 'Jigawa', code: 'JI' },
          { id: 'ng-kaduna', type: 'STATE', name: 'Kaduna', code: 'KD' },
          { id: 'ng-kano', type: 'STATE', name: 'Kano', code: 'KN' },
          { id: 'ng-katsina', type: 'STATE', name: 'Katsina', code: 'KT' },
          { id: 'ng-kebbi', type: 'STATE', name: 'Kebbi', code: 'KE' },
          { id: 'ng-kogi', type: 'STATE', name: 'Kogi', code: 'KO' },
          { id: 'ng-kwara', type: 'STATE', name: 'Kwara', code: 'KW' },
          lagosGranular,
          { id: 'ng-nasarawa', type: 'STATE', name: 'Nasarawa', code: 'NA' },
          { id: 'ng-niger', type: 'STATE', name: 'Niger', code: 'NI' },
          { id: 'ng-ogun', type: 'STATE', name: 'Ogun', code: 'OG' },
          { id: 'ng-ondo', type: 'STATE', name: 'Ondo', code: 'ON' },
          { id: 'ng-osun', type: 'STATE', name: 'Osun', code: 'OS' },
          { id: 'ng-oyo', type: 'STATE', name: 'Oyo', code: 'OY' },
          { id: 'ng-plateau', type: 'STATE', name: 'Plateau', code: 'PL' },
          { id: 'ng-rivers', type: 'STATE', name: 'Rivers', code: 'RI' },
          { id: 'ng-sokoto', type: 'STATE', name: 'Sokoto', code: 'SO' },
          { id: 'ng-taraba', type: 'STATE', name: 'Taraba', code: 'TA' },
          { id: 'ng-yobe', type: 'STATE', name: 'Yobe', code: 'YO' },
          { id: 'ng-zamfara', type: 'STATE', name: 'Zamfara', code: 'ZA' },
          fctGranular,
        ],
      },
      {
        id: 'ghana',
        type: 'COUNTRY',
        name: 'Ghana',
        code: 'GH',
        isCovered: true,
        children: [
          { id: 'gh-ahafo', type: 'STATE', name: 'Ahafo', code: 'AH' },
          { id: 'gh-ashanti', type: 'STATE', name: 'Ashanti', code: 'AS' },
          { id: 'gh-bono', type: 'STATE', name: 'Bono', code: 'BO' },
          { id: 'gh-bono-east', type: 'STATE', name: 'Bono East', code: 'BE' },
          { id: 'gh-central', type: 'STATE', name: 'Central', code: 'CE' },
          { id: 'gh-eastern', type: 'STATE', name: 'Eastern', code: 'EA' },
          accraGranular,
          { id: 'gh-northern', type: 'STATE', name: 'Northern', code: 'NO' },
          { id: 'gh-north-east', type: 'STATE', name: 'North East', code: 'NE' },
          { id: 'gh-oti', type: 'STATE', name: 'Oti', code: 'OT' },
          { id: 'gh-savannah', type: 'STATE', name: 'Savannah', code: 'SA' },
          { id: 'gh-upper-east', type: 'STATE', name: 'Upper East', code: 'UE' },
          { id: 'gh-upper-west', type: 'STATE', name: 'Upper West', code: 'UW' },
          { id: 'gh-volta', type: 'STATE', name: 'Volta', code: 'VO' },
          { id: 'gh-western', type: 'STATE', name: 'Western', code: 'WE' },
          { id: 'gh-western-north', type: 'STATE', name: 'Western North', code: 'WN' },
        ],
      },
      {
        id: 'kenya',
        type: 'COUNTRY',
        name: 'Kenya',
        code: 'KE',
        isCovered: true,
        children: [
          { id: 'ke-baringo', type: 'STATE', name: 'Baringo', code: 'BR' },
          { id: 'ke-bomet', type: 'STATE', name: 'Bomet', code: 'BM' },
          { id: 'ke-bungoma', type: 'STATE', name: 'Bungoma', code: 'BG' },
          { id: 'ke-busia', type: 'STATE', name: 'Busia', code: 'BS' },
          { id: 'ke-elgeyo-marakwet', type: 'STATE', name: 'Elgeyo-Marakwet', code: 'EM' },
          { id: 'ke-embu', type: 'STATE', name: 'Embu', code: 'EB' },
          { id: 'ke-garissa', type: 'STATE', name: 'Garissa', code: 'GA' },
          { id: 'ke-homa-bay', type: 'STATE', name: 'Homa Bay', code: 'HB' },
          { id: 'ke-isiolo', type: 'STATE', name: 'Isiolo', code: 'IS' },
          { id: 'ke-kajiado', type: 'STATE', name: 'Kajiado', code: 'KJ' },
          { id: 'ke-kakamega', type: 'STATE', name: 'Kakamega', code: 'KK' },
          { id: 'ke-kericho', type: 'STATE', name: 'Kericho', code: 'KR' },
          { id: 'ke-kiambu', type: 'STATE', name: 'Kiambu', code: 'KB' },
          { id: 'ke-kilifi', type: 'STATE', name: 'Kilifi', code: 'KF' },
          { id: 'ke-kirinyaga', type: 'STATE', name: 'Kirinyaga', code: 'KY' },
          { id: 'ke-kisii', type: 'STATE', name: 'Kisii', code: 'KI' },
          { id: 'ke-kisumu', type: 'STATE', name: 'Kisumu', code: 'KU' },
          { id: 'ke-kitui', type: 'STATE', name: 'Kitui', code: 'KT' },
          { id: 'ke-kwale', type: 'STATE', name: 'Kwale', code: 'KW' },
          { id: 'ke-laikipia', type: 'STATE', name: 'Laikipia', code: 'LK' },
          { id: 'ke-lamu', type: 'STATE', name: 'Lamu', code: 'LM' },
          { id: 'ke-machakos', type: 'STATE', name: 'Machakos', code: 'MC' },
          { id: 'ke-makueni', type: 'STATE', name: 'Makueni', code: 'MK' },
          { id: 'ke-mandera', type: 'STATE', name: 'Mandera', code: 'MD' },
          { id: 'ke-marsabit', type: 'STATE', name: 'Marsabit', code: 'MR' },
          { id: 'ke-meru', type: 'STATE', name: 'Meru', code: 'ME' },
          { id: 'ke-migori', type: 'STATE', name: 'Migori', code: 'MI' },
          { id: 'ke-mombasa', type: 'STATE', name: 'Mombasa', code: 'MM' },
          { id: 'ke-muranga', type: 'STATE', name: "Murang'a", code: 'MU' },
          nairobiGranular,
          { id: 'ke-nakuru', type: 'STATE', name: 'Nakuru', code: 'NK' },
          { id: 'ke-nyandarua', type: 'STATE', name: 'Nyandarua', code: 'NY' },
          { id: 'ke-nyamira', type: 'STATE', name: 'Nyamira', code: 'NA' },
          { id: 'ke-nandi', type: 'STATE', name: 'Nandi', code: 'ND' },
          { id: 'ke-narok', type: 'STATE', name: 'Narok', code: 'NR' },
          { id: 'ke-nyamira', type: 'STATE', name: 'Nyamira', code: 'NM' },
          { id: 'ke-nyeri', type: 'STATE', name: 'Nyeri', code: 'NR2' },
          { id: 'ke-samburu', type: 'STATE', name: 'Samburu', code: 'SA' },
          { id: 'ke-siaya', type: 'STATE', name: 'Siaya', code: 'SI' },
          { id: 'ke-taita-taveta', type: 'STATE', name: 'Taita-Taveta', code: 'TT' },
          { id: 'ke-tana-river', type: 'STATE', name: 'Tana River', code: 'TR' },
          { id: 'ke-tharaka-nithi', type: 'STATE', name: 'Tharaka-Nithi', code: 'TN' },
          { id: 'ke-trans-nzoia', type: 'STATE', name: 'Trans Nzoia', code: 'TZ' },
          { id: 'ke-turkana', type: 'STATE', name: 'Turkana', code: 'TU' },
          { id: 'ke-uasin-gishu', type: 'STATE', name: 'Uasin Gishu', code: 'UG' },
          { id: 'ke-vihiga', type: 'STATE', name: 'Vihiga', code: 'VH' },
          { id: 'ke-wajir', type: 'STATE', name: 'Wajir', code: 'WJ' },
          { id: 'ke-west-pokot', type: 'STATE', name: 'West Pokot', code: 'WP' },
        ],
      },
      {
        id: 'south-africa',
        type: 'COUNTRY',
        name: 'South Africa',
        code: 'ZA',
        isCovered: true,
        children: [
          { id: 'za-eastern-cape', type: 'STATE', name: 'Eastern Cape', code: 'EC' },
          { id: 'za-free-state', type: 'STATE', name: 'Free State', code: 'FS' },
          { id: 'za-gauteng', type: 'STATE', name: 'Gauteng', code: 'GP' },
          { id: 'za-kwazulu-natal', type: 'STATE', name: 'KwaZulu-Natal', code: 'KZN' },
          { id: 'za-limpopo', type: 'STATE', name: 'Limpopo', code: 'LP' },
          { id: 'za-mpumalanga', type: 'STATE', name: 'Mpumalanga', code: 'MP' },
          { id: 'za-north-west', type: 'STATE', name: 'North West', code: 'NW' },
          { id: 'za-northern-cape', type: 'STATE', name: 'Northern Cape', code: 'NC' },
          { id: 'za-western-cape', type: 'STATE', name: 'Western Cape', code: 'WC' },
        ],
      },
    ],
  },
  {
    id: 'north-america',
    type: 'CONTINENT',
    name: 'North America',
    code: 'NA',
    isCovered: true,
    children: [
      {
        id: 'usa',
        type: 'COUNTRY',
        name: 'United States',
        code: 'US',
        isCovered: true,
        children: [
          { id: 'us-alabama', type: 'STATE', name: 'Alabama', code: 'AL' },
          { id: 'us-alaska', type: 'STATE', name: 'Alaska', code: 'AK' },
          { id: 'us-arizona', type: 'STATE', name: 'Arizona', code: 'AZ' },
          { id: 'us-arkansas', type: 'STATE', name: 'Arkansas', code: 'AR' },
          { id: 'us-california', type: 'STATE', name: 'California', code: 'CA' },
          { id: 'us-colorado', type: 'STATE', name: 'Colorado', code: 'CO' },
          { id: 'us-connecticut', type: 'STATE', name: 'Connecticut', code: 'CT' },
          { id: 'us-delaware', type: 'STATE', name: 'Delaware', code: 'DE' },
          { id: 'us-florida', type: 'STATE', name: 'Florida', code: 'FL' },
          { id: 'us-georgia', type: 'STATE', name: 'Georgia', code: 'GA' },
          { id: 'us-hawaii', type: 'STATE', name: 'Hawaii', code: 'HI' },
          { id: 'us-idaho', type: 'STATE', name: 'Idaho', code: 'ID' },
          { id: 'us-illinois', type: 'STATE', name: 'Illinois', code: 'IL' },
          { id: 'us-indiana', type: 'STATE', name: 'Indiana', code: 'IN' },
          { id: 'us-iowa', type: 'STATE', name: 'Iowa', code: 'IA' },
          { id: 'us-kansas', type: 'STATE', name: 'Kansas', code: 'KS' },
          { id: 'us-kentucky', type: 'STATE', name: 'Kentucky', code: 'KY' },
          { id: 'us-louisiana', type: 'STATE', name: 'Louisiana', code: 'LA' },
          { id: 'us-maine', type: 'STATE', name: 'Maine', code: 'ME' },
          { id: 'us-maryland', type: 'STATE', name: 'Maryland', code: 'MD' },
          { id: 'us-massachusetts', type: 'STATE', name: 'Massachusetts', code: 'MA' },
          { id: 'us-michigan', type: 'STATE', name: 'Michigan', code: 'MI' },
          { id: 'us-minnesota', type: 'STATE', name: 'Minnesota', code: 'MN' },
          { id: 'us-mississippi', type: 'STATE', name: 'Mississippi', code: 'MS' },
          { id: 'us-missouri', type: 'STATE', name: 'Missouri', code: 'MO' },
          { id: 'us-montana', type: 'STATE', name: 'Montana', code: 'MT' },
          { id: 'us-nebraska', type: 'STATE', name: 'Nebraska', code: 'NE' },
          { id: 'us-nevada', type: 'STATE', name: 'Nevada', code: 'NV' },
          { id: 'us-new-hampshire', type: 'STATE', name: 'New Hampshire', code: 'NH' },
          { id: 'us-new-jersey', type: 'STATE', name: 'New Jersey', code: 'NJ' },
          { id: 'us-new-mexico', type: 'STATE', name: 'New Mexico', code: 'NM' },
          { id: 'us-new-york', type: 'STATE', name: 'New York', code: 'NY' },
          { id: 'us-north-carolina', type: 'STATE', name: 'North Carolina', code: 'NC' },
          { id: 'us-north-dakota', type: 'STATE', name: 'North Dakota', code: 'ND' },
          { id: 'us-ohio', type: 'STATE', name: 'Ohio', code: 'OH' },
          { id: 'us-oklahoma', type: 'STATE', name: 'Oklahoma', code: 'OK' },
          { id: 'us-oregon', type: 'STATE', name: 'Oregon', code: 'OR' },
          { id: 'us-pennsylvania', type: 'STATE', name: 'Pennsylvania', code: 'PA' },
          { id: 'us-rhode-island', type: 'STATE', name: 'Rhode Island', code: 'RI' },
          { id: 'us-south-carolina', type: 'STATE', name: 'South Carolina', code: 'SC' },
          { id: 'us-south-dakota', type: 'STATE', name: 'South Dakota', code: 'SD' },
          { id: 'us-tennessee', type: 'STATE', name: 'Tennessee', code: 'TN' },
          { id: 'us-texas', type: 'STATE', name: 'Texas', code: 'TX' },
          { id: 'us-utah', type: 'STATE', name: 'Utah', code: 'UT' },
          { id: 'us-vermont', type: 'STATE', name: 'Vermont', code: 'VT' },
          { id: 'us-virginia', type: 'STATE', name: 'Virginia', code: 'VA' },
          { id: 'us-washington', type: 'STATE', name: 'Washington', code: 'WA' },
          { id: 'us-west-virginia', type: 'STATE', name: 'West Virginia', code: 'WV' },
          { id: 'us-wisconsin', type: 'STATE', name: 'Wisconsin', code: 'WI' },
          { id: 'us-wyoming', type: 'STATE', name: 'Wyoming', code: 'WY' },
        ],
      },
      {
        id: 'canada',
        type: 'COUNTRY',
        name: 'Canada',
        code: 'CA',
        isCovered: true,
        children: [
          { id: 'ca-alberta', type: 'STATE', name: 'Alberta', code: 'AB' },
          { id: 'ca-british-columbia', type: 'STATE', name: 'British Columbia', code: 'BC' },
          { id: 'ca-manitoba', type: 'STATE', name: 'Manitoba', code: 'MB' },
          { id: 'ca-new-brunswick', type: 'STATE', name: 'New Brunswick', code: 'NB' },
          { id: 'ca-newfoundland-labrador', type: 'STATE', name: 'Newfoundland and Labrador', code: 'NL' },
          { id: 'ca-northwest-territories', type: 'STATE', name: 'Northwest Territories', code: 'NT' },
          { id: 'ca-nova-scotia', type: 'STATE', name: 'Nova Scotia', code: 'NS' },
          { id: 'ca-nunavut', type: 'STATE', name: 'Nunavut', code: 'NU' },
          { id: 'ca-ontario', type: 'STATE', name: 'Ontario', code: 'ON' },
          { id: 'ca-prince-edward-island', type: 'STATE', name: 'Prince Edward Island', code: 'PE' },
          { id: 'ca-quebec', type: 'STATE', name: 'Quebec', code: 'QC' },
          { id: 'ca-saskatchewan', type: 'STATE', name: 'Saskatchewan', code: 'SK' },
          { id: 'ca-yukon', type: 'STATE', name: 'Yukon', code: 'YT' },
        ],
      },
    ],
  },
  {
    id: 'europe',
    type: 'CONTINENT',
    name: 'Europe',
    code: 'EU',
    isCovered: true,
    children: [
      {
        id: 'united-kingdom',
        type: 'COUNTRY',
        name: 'United Kingdom',
        code: 'GB',
        isCovered: true,
        children: [
          { id: 'gb-england', type: 'STATE', name: 'England', code: 'ENG' },
          { id: 'gb-northern-ireland', type: 'STATE', name: 'Northern Ireland', code: 'NIR' },
          { id: 'gb-scotland', type: 'STATE', name: 'Scotland', code: 'SCT' },
          { id: 'gb-wales', type: 'STATE', name: 'Wales', code: 'WLS' },
        ],
      },
    ],
  },
  {
    id: 'asia',
    type: 'CONTINENT',
    name: 'Asia',
    code: 'AS',
    isCovered: true,
    children: [
      {
        id: 'uae',
        type: 'COUNTRY',
        name: 'United Arab Emirates',
        code: 'AE',
        isCovered: true,
        children: [
          { id: 'ae-abu-dhabi', type: 'STATE', name: 'Abu Dhabi', code: 'AD' },
          { id: 'ae-ajman', type: 'STATE', name: 'Ajman', code: 'AJ' },
          { id: 'ae-dubai', type: 'STATE', name: 'Dubai', code: 'DU' },
          { id: 'ae-fujairah', type: 'STATE', name: 'Fujairah', code: 'FU' },
          { id: 'ae-ras-al-khaimah', type: 'STATE', name: 'Ras Al Khaimah', code: 'RK' },
          { id: 'ae-sharjah', type: 'STATE', name: 'Sharjah', code: 'SH' },
          { id: 'ae-umm-al-quwain', type: 'STATE', name: 'Umm Al Quwain', code: 'UQ' },
        ],
      },
    ],
  },
  {
    id: 'oceania',
    type: 'CONTINENT',
    name: 'Oceania',
    code: 'OC',
    isCovered: true,
    children: [
      {
        id: 'australia',
        type: 'COUNTRY',
        name: 'Australia',
        code: 'AU',
        isCovered: true,
        children: [
          { id: 'au-australian-capital-territory', type: 'STATE', name: 'Australian Capital Territory', code: 'ACT' },
          { id: 'au-new-south-wales', type: 'STATE', name: 'New South Wales', code: 'NSW' },
          { id: 'au-northern-territory', type: 'STATE', name: 'Northern Territory', code: 'NT' },
          { id: 'au-queensland', type: 'STATE', name: 'Queensland', code: 'QLD' },
          { id: 'au-south-australia', type: 'STATE', name: 'South Australia', code: 'SA' },
          { id: 'au-tasmania', type: 'STATE', name: 'Tasmania', code: 'TAS' },
          { id: 'au-victoria', type: 'STATE', name: 'Victoria', code: 'VIC' },
          { id: 'au-western-australia', type: 'STATE', name: 'Western Australia', code: 'WA' },
        ],
      },
    ],
  },
];
